name: clip
channels:
  - conda-forge
  - pytorch
  - numba
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - cudatoolkit=11.1
  - torchvision
  - faiss-gpu
  - pip
  - pip:
    - -r requirements.txt